#ifndef CHALLENGER604LOGIC_GLOBAL_H
#define CHALLENGER604LOGIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHALLENGER604LOGIC_LIBRARY)
#  define CHALLENGER604LOGICSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHALLENGER604LOGICSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHALLENGER604LOGIC_GLOBAL_H
